[DEFAULT]
PRODUCT_COMPONENT = backend
PIPELINE_STACK_NAME = ala-${PRODUCT_NAME}-${PRODUCT_COMPONENT}-pipeline-${ENVIRONMENT}
DATABASE_STACK_NAME = ala-${PRODUCT_NAME}-database-${ENVIRONMENT}
HELM_RELEASE_NAME = ala-doi-${ENVIRONMENT}
CERTIFICATE_ARN = arn:aws:acm:ap-southeast-2:736913556139:certificate/efa73382-d34b-4091-a918-a303333e7a4c
DOMAIN_NAME = ${PRODUCT_NAME}.${HOSTED_ZONE}
AUTO_DEPLOY = true
SLACK_DEPLOY_NOTIFICATION = true
SLACK_ALERT_CHANNEL = testing-deployments

;Doi config file properties
DEPLOYMENT_ENV = prod

SECURITY_CORE_ROLEATTRIBUTE = ala:role
SECURITY_CORE_AUTHCOOKIENAME = ALA-Auth-Test
SECURITY_CORE_AFFILIATIONSURVEY_ENABLED = true

SECURITY_COOKIE_ENABLED = true
SECURITY_COOKIE_DOMAIN = .ala.org.au

SECURITY_CAS_CASSERVERNAME = https://auth-test.ala.org.au
SECURITY_CAS_CASSERVERURLPREFIX = https://auth-test.ala.org.au/cas
SECURITY_CAS_CASSERVERLOGINURL = https://auth-test.ala.org.au/cas/login
SECURITY_CAS_CASSERVERLOGOUTURL = https://auth-test.ala.org.au/cas/logout
SECURITY_CAS_APPSERVERNAME = https://doi.test.ala.org.au
SECURITY_CAS_LOGINURL = https://auth-test.ala.org.au/cas/login
SECURITY_CAS_LOGOUTURL = https://auth-test.ala.org.au/cas/logout

SECURITY_OIDC_CLIENTID = 63jti007ijhbhsvg0ihbgc9ai4
SECURITY_OIDC_SECRET = secret
SECURITY_OIDC_DISCOVERYURI = https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_OOXU9GW39/.well-known/openid-configuration
SECURITY_OIDC_SCOPE = "openid profile email ala/attrs ala/roles"
SECURITY_OIDC_ALAUSERIDCLAIM = username
SECURITY_OIDC_LOGOUTACTION = cognito
SECURITY_OIDC_LOGOUTURL = https://auth-secure.auth.ap-southeast-2.amazoncognito.com/logout

SECURITY_JWT_DISCOVERYURI = https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_OOXU9GW39/.well-known/openid-configuration
SECURITY_JWT_CLIENTID = 63jti007ijhbhsvg0ihbgc9ai4
SECURITY_JWT_ROLESFROMACCESSTOKEN = true
SECURITY_JWT_USERIDCLAIM = username
SECURITY_JWT_ROLECLAIMS = cognito:groups

SECURITY_APIKEY_ENABLED = true
SECURITY_APIKEY_AUTH_SERVICEURL = https://auth-test.ala.org.au/apikey/
SECURITY_APIKEY_CHECK_SERVICEURL = https://auth-test.ala.org.au/apikey/ws/check?apikey=
SECURITY_APIKEY_USERDETAILS_SERVICEURL = https://auth-test.ala.org.au/userdetails/

WEBSERVICE_JWT = true
WEBSERVICE_JWTSCOPES = "ala/internal users/read ala/attrs"
WEBSERVICE_CLIENTID =
WEBSERVICE_CLIENTSECRET = clientid

USERDETAILS_URL = https://api.test.ala.org.au/userdetails/cognito/

LOGGING_CONFIG = /data/doi-service/config/logback.xml

SERVERURL = https://doi.test.ala.org.au
SERVERNAME = https://doi.test.ala.org.au

SERVER_PORT = 8080
SERVER_CONTEXTPATH =

;recipient email
SUPPORT_EMAIL = support@ala.org.au
;sender email
SUPPORT_NOREPLY = no-reply@ala.org.au
MAIL_ENABLED = true
MAIL_SES_ENABLED = true

ANDS_DOI_SERVICE_URL = https://services.ands.org.au/doi/1.1/
ANDS_DOI_APP_ID = cd07d958eb1e2881a13e61db23d081dabc0ac50c
ANDS_DOI_KEY = key
ANDS_DOI_CLIENT_ID = 68

DATACITE_DOI_SERVICE_BASEAPIURL = https://api.test.datacite.org/
DATACITE_DOI_SERVICE_USER = ALA.REPO
DATACITE_DOI_SERVICE_PASSWORD = password
DATACITE_DOI_SERVICE_PREFIX = 10.80416
DATACITE_DOI_SERVICE_SHOULDER = ala

ALA_BASE_URL = https://www.ala.org.au

SKIN_LAYOUT = ala-main
SKIN_FLUIDLAYOUT =
SKIN_ORGNAMELONG = "Atlas of Living Australia"
SKIN_ORGNAMESHORT = ALA
SKIN_FAVICON = https://www.ala.org.au/app/uploads/2019/01/cropped-favicon-32x32.png

HEADERANDFOOTER_BASEURL = https://www-test-2023.ala.org.au/commonui-bs3-2019
HEADERANDFOOTER_VERSION = 2

DOI_SERVICE_PROVIDER_MAPPING = DATACITE
DOI_STORAGE_PROVIDER = S3
DOI_DISPLAYTEMPLATES = template,biocache,phylolink,csdm
DOI_RESOLVERURL = https://handle.stage.datacite.org/

GRAILS_SERVERURL = https://doi.test.ala.org.au
GRAILS_PLUGIN_AWSSDK_REGION = ap-southeast-2
GRAILS_PLUGIN_AWSSDK_S3_ACCESSKEY =
GRAILS_PLUGIN_AWSSDK_S3_SECRETKEY =
GRAILS_PLUGIN_AWSSDK_S3_BUCKET = ala-doi-testing
GRAILS_PLUGIN_AWSSDK_S3_REGION = ap-southeast-2

FILE_STORE = /data/doi-service/files

GOOGLEANALYTICSID = UA-4355440-4

DATASOURCE_URL = jdbc:postgresql://localhost/doi?autoReconnect=true&connectTimeout=0&useUnicode=true&characterEncoding=UTF-8
DATASOURCE_USERNAME = dbmaster
DATASOURCE_PASSWORD = password

COLLECTIONS_BASEURL = https://collections-test.ala.org.au

BIOCACHE_WSURL = https://api.test.ala.org.au/occurrences

SWAGGER_INFO_DESCRIPTION = "Generate DOIs for ALA applications"
SWAGGER_INFO_VERSION = 1.0
SWAGGER_INFO_TITLE = "ALA DOI service"
SWAGGER_INFO_TERMSOFSERVICES = https://www.ala.org.au/who-we-are/terms-of-use/
SWAGGER_INFO_CONTACT_NAME = "ALA Support"
SWAGGER_INFO_CONTACT_URL = https://www.ala.org.au
SWAGGER_INFO_CONTACT_EMAIL = support@ala.org.au

OPENAPI_TERMS = https://www.ala.org.au/terms-of-use/
OPENAPI_CONTACT_EMAIL = support@ala.org.au
OPENAPI_COMPONENTS_SECURITY_OAUTH2_BASEURL = https://auth-secure.auth.ap-southeast-2.amazoncognito.com/oauth2

USERDETAILS_WEBURL = https://userdetails.test.ala.org.au/
USERDETAILS_APIURL = https://api.test.ala.org.au/userdetails/cognito/

ELASTICSEARCH_HOST = elasticsearch-doi-${CLEAN_BRANCH}.elasticsearch.svc.cluster.local

CPU_REQUEST = 1
MEMORY_REQUEST = 4096Mi
CPU_LIMIT = 1
MEMORY_LIMIT = 4096Mi

POD_ENVIRONMENT = production
HEAP_SIZE_INITIAL = 3g
HEAP_SIZE_MAX = 3g

[development]
# code pipeline
PIPELINE_STACK_NAME = ala-${PRODUCT_NAME}-${PRODUCT_COMPONENT}-pipeline-${CLEAN_BRANCH}
; Update the database stack name if creating a new database stack for feature branch
DATABASE_STACK_NAME = ala-${PRODUCT_NAME}-database-${CLEAN_BRANCH}
#DATABASE_STACK_NAME = ala-${PRODUCT_NAME}-database-testing
# also override the secret we're using so we get the testingDB password 
#SECRET_NAME = ${PRODUCT_NAME}-testing
DOMAIN_NAME = ${PRODUCT_NAME}-${CLEAN_BRANCH}.${HOSTED_ZONE}
HELM_RELEASE_NAME = ala-doi-${CLEAN_BRANCH}
CERTIFICATE_ARN = arn:aws:acm:ap-southeast-2:748909248546:certificate/969309c3-9c24-4fc8-9e16-10334e82bbd4

;Doi config file properties


POD_ENVIRONMENT = development
HEAP_SIZE_INITIAL = 3g
HEAP_SIZE_MAX = 3g

CPU_REQUEST = 1
MEMORY_REQUEST = 4096Mi
CPU_LIMIT = 1
MEMORY_LIMIT = 4096Mi

[testing]
CERTIFICATE_ARN = arn:aws:acm:ap-southeast-2:748909248546:certificate/d866578c-8ad1-4462-9485-14472e1410fc
DOMAIN_NAME = ${PRODUCT_NAME}-temp.${HOSTED_ZONE}

;Doi config file properties


POD_ENVIRONMENT = test
HEAP_SIZE_INITIAL = 3g
HEAP_SIZE_MAX = 3g

CPU_REQUEST = 1
MEMORY_REQUEST = 4096Mi
CPU_LIMIT = 1
MEMORY_LIMIT = 4096Mi

[staging]

AUTO_DEPLOY = false
DOMAIN_NAME = ${PRODUCT_NAME}-staging.${HOSTED_ZONE}

MAIL_ENABLED = false

[production]

AUTO_DEPLOY = false
DOMAIN_NAME = ${PRODUCT_NAME}.${HOSTED_ZONE}
SLACK_ALERT_CHANNEL = deployments

CAS_CLIENT_ID = 1cUbmqXfQdBweHAPTNp7jKHRQyzJev0sfNO5
CAS_S2S_CLIENT_ID = 1cUbmqXfQdBweHAPTNp7jKHRQyzJev0sfNO5

MAIL_ENABLED = true